### ISSUE TITLE
auto-update samba secrets

### ISSUE THREAD

**Issue by ptulpen** [msktutil/msktutil#131]
Hello,
we have had it now several times, that the samba did not work anymore, probably because the computer account changed
We could fix this by :
 msktutil update --set-samba-secret --enctypes 0x10

But a automated way would be better of course
I forced a password change by msktutil update and tried it with :
 msktutil auto-update --set-samba-secret --enctypes 0x10 , which took some time but did not work.
The manual way without update worked again

So is there a elegant way to update samba secrets automatically ?
Corrent idea is to make a cronjob like
msktutil auto-update &&  msktutil update --set-samba-secret --enctypes 0x10 
but I think there might be better ways :)

**Comment by dkobras** [comment]
For your use-case `msktutil auto-update --set-samba-secret (...)` should be the way to go. If `msktutil update --set-samba-secret (...)` works for you, so should `auto-update`. Apart from the check whether the computer password has aged, the code paths for both commands are identical.

From your description, I'd suspect that `msktutil` might have been called with different sets of environment variables (eg. interactively and from a cron job), and Samba's `net` command couldn't be found in `PATH` for some invocations. Due to bug #124, this not only leaves Samba broken, but the domain join as a whole, and needs admin interaction to recover. (Surely not the root cause of your problems, but it currently makes it harder to clean up the mess.) Also, when using Samba with `mskutil`, make sure to set Samba's `machine password timeout` to zero. Otherwise, both password update mechanisms might interfere.

**Comment by dkobras** [comment]
Assuming this is issue is address by the previous comment. Please reopen (ideally with `--verbose` output from `update` and `auto-update` runs if you still face problems despite identical environments.
