### ISSUE TITLE
--base cannot include domain (Error ldap_add_ext_s)

### ISSUE THREAD

**Issue by dirkpetersen** [msktutil/msktutil#140]
Using newer versions of msktutil  (starting 1.0 ?) I am getting this error 

```
msktutil create --base "ou=Computers,ou=Department,dc=organization,dc=org"
No computer account for moin found, creating a new one.
Error: ldap_add_ext_s failed (No such object)
	additional info: 0000208D: NameErr: DSID-03100238, problem 2001 (NO_OBJECT), data 0, best match of:
	',dc=organization,dc=org'

Error: ldap_add_ext_s failed (No such object)
```

this works fine however:

```
msktutil create --base "ou=Computers,ou=Department"
```

**Comment by dkobras** [comment]
Thanks for the report!
As far as I can tell, `-b` has been treated as a relative path since version 0.4 (commit bb585d536a838ed88878c5ae0f527076cbd8bb79 from almost ten years ago), and it's also documented this way. But given that other LDAP tools commonly use this option to specifies a base DN, this behaviour certainly violates the principle of least surprise. Also, it should be easy to fix: We can just skip appending the base DN if the given OU already ends with it.

**Comment by dkobras** [comment]
PR #141 should address this issue.
