### ISSUE TITLE
update additional service keytab

### ISSUE THREAD

**Issue by uli42** [msktutil/msktutil#142]
We are using a Gitlab installation that requires a separate keytab file which must be readable by the "git" user (see https://docs.gitlab.com/ee/integration/kerberos.html). Of course we can copy the existing /etc/krb5.keytab to the desired path and adjust the permissions. However, this will work for some time and then break because the krb5.keytab gets frequently updated by msktutil.

I am looking for a way to update the service keytab via msktutil as well. Is that possible with the current option set?

PS: We can copy the krb5.keytab via cron but then the service keytab is not restricted to the service principals but contains _all_ principals which I would like to avoid. I tried to extract the relevant keys from the krb5.keytab and feed them to ktutil but that tool is not cooperative when it comes to passing keys via stdin...

**Comment by dkobras** [comment]
Sure, there's no need to run `msktutil` as the `root` user, unless required by filesystem permissions. You can just create a separate keytab file, owned by the `git` user, and invoke `msktutil` from this account as well. However, in this case, your service principals should be associated with a separate service account in AD rather than the machine account. Here's an example invocation (taken from the man page) for a HTTP principal attached to the service account `srv-http` in AD:

```
msktutil create --use-service-account --service HTTP/hostname.example.com --keytab /etc/apache/krb5.keytab --account-name srv-http --no-pac
```

**Comment by uli42** [comment]
I don't have the possibility to attach the service principals to anything else than the machine account. So what's can I do then?

**Comment by dkobras** [comment]
If all your services need to share the machine account, each service needs to have access to the machine credentials: Provide your `git` account with read access to `/etc/krb5.keytab`. (It's not the option I'd recommend though. Rather get policy fixed to allow creation of dedicated service accounts.)

**Comment by uli42** [comment]
Ok, thank you.

I'd like suggest a parameter like --service-keytabs or --additional-keytabs or similar to write multiple keytabs at once (while retaining their specific permissions)? This way we could keep several keytabs in sync.

**Comment by dkobras** [comment]
If all service principals derive from the same machine account, there's no point in keeping separate keytabs. The keys are identical. In order to share this information between multiple parties, just open up file permissions, and be done with it. There's just no benefit from replication at this point.

**Comment by michael-o** [comment]
@dkobras Pretty much nailed all possibilities here. Either grant access to to machine keytab or use a service account with the SPN.
