### ISSUE TITLE
msDs-supportedEncryptionTypes not set in certain situations

### ISSUE THREAD

**Issue by michael-o** [msktutil/msktutil#160]
Merge issues/157 and create a machine account with a domain admin account which cannot set:
```
 -- modify_ext: ldap_modify_ext_s failed (Insufficient access)
WARNING: ldap modification of ...
         failed while trying to change msDs-supportedEncryptionTypes to 28.
         Error was: Insufficient access
         --> Do you have enough privileges?
         --> You might try re-"kinit"ing.
         Continuing anyway ...
```

Note: My domain admin account does not has this permission for some reason which does not matter here.

Since the attribute has not been set, perform an update:
```
...
 -- ldap_set_supportedEncryptionTypes: No need to change msDs-supportedEncryptionTypes they are 28
```

The cause is, it is empty/not present in AD, the value is to the default one, command arg has not been passed and set to default. Both values are identical in memory therefore the ldap set is never run.

It boils down to: mskutil never retries to set a non-existing value (`msDs-supportedEncryptionTypes`) in AD.

**Comment by michael-o** [comment]
Since this value is not set now, I see with kvno and klist:
```
        Etype (Skey, TKT): DEPRECATED:arcfour-hmac, DEPRECATED:arcfour-hmac
13.02.2021 12:24:56  13.02.2021 22:24:15  host/deblndw013x@AD001.SIEMENS.NET
```

**Comment by michael-o** [comment]
I do know understand why this happens. According to [this](https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/decrypting-the-selection-of-supported-kerberos-encryption-types/ba-p/1628797) source, an absent  `msDs-supportedEncryptionTypes` is the same a zero which is the same as not default, thus `RC4_HMAC_MD5`. So believe that https://github.com/msktutil/msktutil/blob/f7dede0c14cbf5a24c75d7c83c233d26b92ff296/msktldap.cpp#L605-L609 must be set to `RC4_HMAC_MD5`. This has also implications on #157.

**Comment by michael-o** [comment]
@oflebbe Please tell me what you think?

**Comment by oflebbe** [comment]
@michael-o The reference you are citing does only handle cases where msDs-supportedEncryptionTypes is not empty.

According to https://lists.samba.org/archive/cifs-protocol/attachments/20100111/e8bb3520/attachment-0001.pdf in the empty case we should use the default encryption types and allow RC4 only if the UF_USE_DES_KEY_ONLY bit is not set in userAccountControl. The lines above implement exactly this if the default are these DES ciphers, as far as I can tell.

Setting RC4 unconditionally would be a huge security risk since it will open for the kerberoast secrutiy vulerability. 

The message above is only a warning, and it does not break anything, right ? 

If I understand all the references correctly: 
If you do not want to see the warning, you need either the msDs-supportedEncryptionTypes on your account correctly populated or if it is absent, you need the rights to  set the attribute msDs-supportedEncryptionTypes . 
It looks like you are asking for a specific workaround for a situation which should not happen.

**Comment by michael-o** [comment]
Let me evalute that...

**Comment by michael-o** [comment]
Thanks for the document, it does clear up a lot. In fact, msktutil is correctly implemented, *but* it is missing crucial information: Since the attribute could not be set, the user does not know which enc types will be used when the keytab is constructed. So your reference and [this](https://github.com/msktutil/msktutil/issues/158#issuecomment-778829829) completely cover this. No workaround necesary, just more information. I will prepare a PR.
